name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  schedule:
    - cron: '30 2 * * 1'

env:
  DOCKERHUB_IMAGE: docker.io/acoby/ansible-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.DOCKERHUB_IMAGE }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }},${{ env.DOCKERHUB_IMAGE }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Checkout github repository
        uses: actions/checkout@v2

      - name: Update Github Workflow to avoid disabling of Github Actions
        uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
